### ISSUE TITLE
Work And Contact Page Link's Broken

### ISSUE THREAD

**Issue by indraantoor** [AbhishekMaira10/AbhishekMaira10.github.io#1]
Work and contact links on your navigation bar on your site "https://www.abhishekmaira.com/" are broken. 

By clicking the links you get a page not found.

**Contact Link**
![contact link](https://user-images.githubusercontent.com/64259328/100498189-77c96c80-3186-11eb-8563-20dec09e4a36.PNG)

**Work Link**
![Work Link](https://user-images.githubusercontent.com/64259328/100498190-78fa9980-3186-11eb-9e01-6aa04bf3ed3f.PNG)

**Comment by AbhishekMaira10** [comment]
I haven't added the code for it yet. I'll add it as soon as I get some time
